name: Docker Image CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: build
        run: docker build . --file Dockerfile --tag tbct/artifactory-jfrog-cli:latest

      - name: Bump version
        uses: remorses/bump-version@js
        id: version
        with:
          version_file: ./VERSION
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
