name: Docker Image CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: build
        run: docker build . --file Dockerfile --tag tbct/artifactory-jfrog-cli:latest

      - name: Bump version
        uses: remorses/bump-version@js
        id: version
        with:
          version_file: ./VERSION
          github_token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Tag the new version
      - name: Tag Repo
        uses: richardsimko/github-tag-action@master
        with:
          tag_name: ${{ steps.version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
